services:
  - type: web
    name: lets-connect
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    releaseCommand: python manage.py migrate
    startCommand: gunicorn Lets_Connect.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: lets-connect.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://lets-connect.onrender.com
